name: Publish
on:
  push:
    branches: [main]

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositiory
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish Package to Github
        run: |
          echo '//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}' > .npmrc
          npm config set registry https://npm.pkg.github.com
          npm publish
      - name: Publish Package to NPM
        run: |
          echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' > .npmrc
          npm config set registry https://registry.npmjs.org
          npm publish --access public